name: matsha_env
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - numpy
  - pandas
  - samtools
  - bowtie2
  - snpeff=5.2
  - scipy
  - ncbi-genome-download
  - biopython
  - gatk4
  - click
  - pytest
  - pip
  - pip:
      - -e .  # Install MATSHA in editable mode via pip